### ISSUE TITLE
Draw cursor on the view

### ISSUE THREAD

**Issue by douwevos** [douwevos/natpad3#21]
The text-model contains a cursor which should be visualized by drawing a line or a rectangle at the corresponding position. The Cursor should be draw in the on_draw method and not on the offscreen-images. The view-position should be calculated in the on_draw method for now as well and be kept as simple as possible. (PS we might later conclude that the view-position should be calculated in the invalidate-lines or another method)

**Comment by gerardvisser** [comment]
Interesting problems arise with variable length characters (like in UTF-8 encoding).
